### ISSUE TITLE
Uncaught ReferenceError: exports is not defined

### ISSUE THREAD

**Issue by Koko2034** [nicojs/stryker-typescript-issue394#1]
Hello everybody!

I'm using your stryker settings, but when I run tests over typescript's class, I always get the same error:

`Uncaught ReferenceError: exports is not defined`

I suppose this reference to "exports" is for our class. 

Could you help me?

**Comment by nicojs** [comment]
I'm not sure why you're posting this here. Did you mean to post it in the main stryker repo?

https://github.com/stryker-mutator/stryker/issues
